name: Trivy PR scan (secrets & vuln)

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches: [ main ]

permissions:
  contents: read
  security-events: write

jobs:
  trivy-scan:
    name: Trivy filesystem scan (secrets + vuln)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout PR head
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          # ensure we scan the PR's branch contents
          ref: ${{ github.head_ref }}

      - name: Run Trivy (install + scan)
        # uses the official Trivy Action which installs Trivy and runs it
        uses: aquasecurity/trivy-action@v0.28.0
        with:
          scan-type: 'fs'
          scan-ref: '.'
          format: 'sarif'
          output: 'trivy-results.sarif'
          severity: 'CRITICAL,HIGH'
          exit-code: '1'        # if Trivy finds HIGH/CRITICAL issues -> exit non-zero -> fail job

      - name: Upload Trivy results to Security (SARIF)
        if: always()
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: 'trivy-results.sarif'
